CREATE TABLE "ROOM" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "CAPACITY" INT NOT NULL,
    "FLOOR" INT NOT NULL,
    "NUMBER" INT NOT NULL,
    "NOTE" VARCHAR(255)
);

CREATE TABLE "GUEST" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "ROOMID" BIGINT REFERENCES ROOM (ID),
    "NAME" VARCHAR(50),
    "SURNAME" VARCHAR(50),
    "IDENTITYCARDNUMBER" VARCHAR(9),
    "GENDER" VARCHAR(6)
);